### ISSUE TITLE
substituir TODAS as imagens referentes a SP que estão na pasta img do tema por equivalentes de BH

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/viradacultural-bh#2]
talvez nem todas sejam usadas, mas na dúvida substitua, se não tiver duvida apague.

dica: usar o editor para procurar em todo o código o nome da imagem.

IMPORTANTE: lembrar do favicon.

**Comment by nicolavieira** [comment]
ok, o que eu fiz:
- substitui os arquivos favicon, icon, icone-app e logo-share
- o arquivo logo-roxo-1024 eu não referência a lugar nenhum no código, então apaguei
- faltam os pins que eu tentei arrumar no GIMP mas ficaram horríveis, eu precisava do vetor para arrumá-los
